evangelisation/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from evangelisation import views



app_name="evangelisation"


urlpatterns = [
    path('', views.evangelisation_app_index, name="evangelisation_app_index"),
    path('<int:annee>', views.evangelisation_app_index, name="evangelisation_app_index"),

    path('operations/<str:type_opera>/', 
        views.evangelisation_app_operations, name="evangelisation_app_operations"),

    path('ajouter/<str:type_opera>/', 
        views.evangelisation_app_form_nbre, name="evangelisation_app_form_nbre"),

    path('ajouter/<str:type_opera>/form_nbre=<int:form_nbre>', 
        views.evangelisation_app_multi_form_type_operation, name="evangelisation_app_multi_form_type_operation"),

    path('modifier/<str:type_opera>-elements/', 
            views.evangelisation_app_operations_models_modifier, 
            name="evangelisation_app_operations_models_modifier"), 

    path('modifier/<str:type_opera>/<int:id>/', 
            views.evangelisation_app_operations_modifier, name="evangelisation_app_operations_modifier"),

    path('supprimer/<str:type_opera>-elements/', 
            views.evangelisation_app_operations_models_supprimer, 
            name="evangelisation_app_operations_models_supprimer"), 

    path('supprimer/<str:type_opera>/', 
            views.evangelisation_app_operations_supprimer, name="evangelisation_app_operations_supprimer"),    

    path('recherche/<str:type_opera>/', 
        views.evangelisation_app_operations_recherche, name="evangelisation_app_operations_recherche"),

            
    path('ajouter/<str:type_opera>/form_nbre=<int:form_nbre>', 
        views.evangelisation_app_operations_ajax, name="evangelisation_app_operations_ajax"),


]

src/urls.py
from fileinput import filename
from re import template
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os


from . import views

urlpatterns = [
    path('evangelisation-admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('', include("accounts.urls")),
    path('evangelisation/', include("evangelisation.urls")),
    path('rapport/', include("rapport.urls")),

]



urlpatterns += static(settings.STATIC_URL,   document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/root/index.html
{% extends 'base.html' %}

{% block titre %}
ASSEMBLE EAUX PAISIBLES | Evangélisations
{% endblock titre %}

{% block content %}
<div class="home">
    <div class="row media-grd media-petit">
        <h2>Bienvenue, <b>{{ request.user }}</b> et content de vous revoir!!!</h2>
    <h4>Cantique des degrés.De David Voici, oh! qu'il est agréable, qu'il est doux pour des frères de demeurer
        ensemble!
        <br>
        <b style="color:rgb(56, 87, 155);">PSAUMES 133:1</b>
    </h4>
    <h4>
        Qu'ils sont beaux sur les montagnes, Les pieds de celui qui apporte de bonnes nouvelles, Qui publie la paix ! De
        celui qui apporte de bonnes nouvelles, Qui publie le salut ! De celui qui dit à Sion : ton Dieu règne ! 
        <br>
        <b style="color: rgb(56, 87, 155);">Esaïe 52:7</b>
    </h4>
    <div class="wrapper-btn">
        <a href="{% url 'user_logout' %}" class="btn btn-link btn-sm">
            <i class='fa fa-sign-out'></i> se déconnecter
        </a>
        <a href="{% url 'evangelisation:evangelisation_app_index' %}" class="btn btn-secondary btn-sm">
            continue
            <i class="fa fa-arrow-right"></i>
        </a>
    </div>
    </div>
</div>
{% endblock content %}