evangelisation/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from evangelisation import views



app_name="evangelisation"


urlpatterns = [
    path('', views.evangelisation_app_index, name="evangelisation_app_index"),
    path('<int:annee>', views.evangelisation_app_index, name="evangelisation_app_index"),

    path('operations/<str:type_opera>/', 
        views.evangelisation_app_operations, name="evangelisation_app_operations"),

    path('ajouter/<str:type_opera>/', 
        views.evangelisation_app_form_nbre, name="evangelisation_app_form_nbre"),

    path('ajouter/<str:type_opera>/form_nbre=<int:form_nbre>', 
        views.evangelisation_app_multi_form_type_operation, name="evangelisation_app_multi_form_type_operation"),

    path('modifier/<str:type_opera>-elements/', 
            views.evangelisation_app_operations_models_modifier, 
            name="evangelisation_app_operations_models_modifier"), 

    path('modifier/<str:type_opera>/<int:id>/', 
            views.evangelisation_app_operations_modifier, name="evangelisation_app_operations_modifier"),

    path('supprimer/<str:type_opera>-elements/', 
            views.evangelisation_app_operations_models_supprimer, 
            name="evangelisation_app_operations_models_supprimer"), 

    path('supprimer/<str:type_opera>/', 
            views.evangelisation_app_operations_supprimer, name="evangelisation_app_operations_supprimer"),    

    path('recherche/<str:type_opera>/', 
        views.evangelisation_app_operations_recherche, name="evangelisation_app_operations_recherche"),

            
    path('ajouter/<str:type_opera>/form_nbre=<int:form_nbre>', 
        views.evangelisation_app_operations_ajax, name="evangelisation_app_operations_ajax"),


]

src/urls.py
from fileinput import filename
from re import template
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import os


from . import views

urlpatterns = [
    path('evangelisation-admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('', include("accounts.urls")),
    path('evangelisation/', include("evangelisation.urls")),
    path('rapport/', include("rapport.urls")),

]



urlpatterns += static(settings.STATIC_URL,   document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evangelisation/views.py
from fileinput import filename
from random import random
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import modelformset_factory
from django.http import JsonResponse
from django.contrib import messages
from django.db.models.query_utils import Q
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


from evangelisation.utils import (get_form_set, get_liste_models_and_template, 
                                redirect_by_form_set, get_liste_models, get_model,
                                get_liste_models_operations, get_model, get_form_model
                                )
from evangelisation.forms import ParticipantForm, FormNbre, EvangForm
from evangelisation.models import Participant, Evangelisation, Site, Person, Suivi, Profile


import datetime

import json
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

@login_required(login_url="user_login")
def evangelisation_app_index(request, annee=None):
    context = dict()
    evang_first = None
    evangs = None
    annees = list()
    annee = None

    
    year = int(datetime.date.today().year)
    for i in [0, 1, 2]:
        annees.append(year-i)

    evangs = Evangelisation.objects.all()
    if 'liste-evang' in request.GET:
        evang_first = Evangelisation.objects.get(id=int(request.GET['liste-evang']))
    else:
        evang_first = evangs.first()

    
    context['evang_first'] = evang_first
    context['evangs'] = evangs
    #context['annees'] = annees
    #context['anne_select'] = annee
    context['select_link'] = 'evangelisation'
    return render(request, 'index.html', context)



@login_required(login_url="user_login")
def evangelisation_app_multi_form_type_operation(request, type_opera, form_nbre):
    form_errors = None
    context = dict()
    model_set = None
    form_set = None

    model_set = get_form_set(type_opera, form_nbre)
    if request.method=='POST':
       form_set = model_set(request.POST)
       if form_set.is_valid():
            if type_opera=='personnes':
                forms = form_set.save(commit=False)
                if forms != []:
                    for instance in forms:
                        instance.save()
                        Suivi.objects.create(person=instance)
                    form_set.save_m2m()
                    messages.success(request, f'Vous avez ajouté {len(form_set)} {type_opera}')
                    return redirect_by_form_set(type_opera)
                else:
                    form_errors = form_set.errors
            else:
                form_set.save()
                messages.success(request, f'Vous avez ajouté {len(form_set)} {type_opera}')
                return redirect_by_form_set(type_opera)
       else:
           form_errors = form_set.errors
    else:
        model = get_model(type_opera)
        form_set = model_set(queryset=model.objects.none())
        
    context = {
        'form_set': form_set,
        'multi': True,
        'form_nbre': int(form_nbre),
        'type_opera': type_opera,
        'form': FormNbre(),
        'form_p': ParticipantForm(),
        'form_errors': form_errors,
    }
    context['select_link'] = 'opérations'

    if type_opera == 'personnes':    
        context['select_link_sub'] = 'opérations-pers'
    elif type_opera == 'sites':
        context['select_link_sub'] = 'opérations-site'
    elif type_opera == 'participants':
        context['select_link_sub'] = 'opérations-part'
    elif type_opera == 'évangelisations':
        context['select_link_sub'] = 'opérations-evang'
    
    return render(request, 'pages/form.html', context)



@login_required(login_url="user_login")
def evangelisation_app_form_nbre(request, type_opera):
    context = dict()
    if request.method=='POST':
        form = FormNbre(request.POST)
        if form.is_valid():
            form_nbre = request.POST['field']
            return redirect('evangelisation:evangelisation_app_multi_form_type_operation', type_opera, form_nbre)
    else:
        form = FormNbre()
    context = {
        'form': form,
        'type_opera': type_opera,
        'select_link': 'evangelisation'
    }
    context['select_link'] = 'opérations'
    if type_opera == 'personnes':    
        context['select_link_sub'] = 'opérations-pers'
    elif type_opera == 'sites':
        context['select_link_sub'] = 'opérations-site'
    elif type_opera == 'participants':
        context['select_link_sub'] = 'opérations-part'
    elif type_opera == 'évangelisations':
        context['select_link_sub'] = 'opérations-evang'
    
    return render(request, 'pages/form.html', context)


@login_required(login_url="user_login")
def evangelisation_app_operations(request, type_opera):
    return get_liste_models_and_template(request, type_opera)


@login_required(login_url="user_login")
def evangelisation_app_operations_recherche(request, type_opera):
    data = dict()
    models = None
    counter = None
    models_template = None
    if type_opera=="personnes":
        if request.GET.get('name') == 'query':
            value = request.GET.get('value')
            models = Person.objects.filter(
                Q(nom_et_prenom__contains=str(value)) 
                | Q(contacts__contains=str(value))
                | Q(quartier_d_habitation__contains=str(value))
                | Q(temoignages__contains=str(value))
                | Q(sujets_de_priere__contains=str(value))
            )
            models_template = render_to_string(
                'pages/personne/table_personne.html', 
                {'models':models}, 
                request=request
            )
        else:
            models = Person.objects.all()
            models_template = render_to_string(
                'pages/personne/table_personne.html', 
                {'models':models}, 
                request=request
            )
    elif type_opera=="participants":
        if request.GET.get('name') == 'query':
            value = request.GET.get('value')
            models = Participant.objects.filter(
                Q(nom_et_prenom__contains=str(value)) 
            )
            models_template = render_to_string(
                'pages/participant/table_participant.html', 
                {'models':models}, 
                request=request
            )
        else:
            models = Participant.objects.all()
            models_template = render_to_string(
                'pages/participant/table_participant.html', 
                {'models':models}, 
                request=request
            )
    elif type_opera=="sites":
        if request.GET.get('name') == 'query':
            value = request.GET.get('value')
            models = Site.objects.filter(
                Q(nom_site_evangelisation__contains=str(value)) 
            )
            models_template = render_to_string(
                'pages/site/table_site.html', 
                {'models':models}, 
                request=request
            )
        else:
            models = Site.objects.all()
            models_template = render_to_string(
                'pages/site/table_site.html', 
                {'models':models}, 
                request=request
            )
    elif type_opera=="évangelisations":
        if request.GET.get('name') == 'query':
            value = request.GET.get('value')
            models = Evangelisation.objects.filter(
                Q(day__contains=str(value)) 
                |Q(site__nom_site_evangelisation__contains=str(value)) 
            )
            models_template = render_to_string(
                'pages/evangelisation/table_evangelisation.html', 
                {'models':models}, 
                request=request
            )
        else:
            models = Evangelisation.objects.all()
            models_template = render_to_string(
                'pages/evangelisation/table_evangelisation.html', 
                {'models':models}, 
                request=request
            )


    if len(models) > 1:
            counter_str = f"{len(models)} resultats"
    else:
        counter_str = f"{len(models)} resultat"
        counter = len(models)
        data['counter'] = counter

    data['counter_str'] = counter_str
    data['models'] = models_template
    return  JsonResponse(data, safe=False)



@login_required(login_url="user_login")
def evangelisation_app_operations_models_supprimer(request, type_opera):
    context = dict()
    if 'selected_action' in request.POST:
        liste = request.POST.getlist('selected_action')
        if request.POST['objects'] == 'supprimer':
            context['models'] = get_liste_models_operations(type_opera, liste)
            context['type_opera'] = type_opera
            return render(request, 'pages/supprimer.html', context)
    else:
        return redirect('evangelisation:evangelisation_app_operations', type_opera)


@login_required(login_url="user_login")
def evangelisation_app_operations_supprimer(request, type_opera):
    if 'user_selected' in request.POST:
        liste = request.POST.getlist('user_selected')
        Model = get_model(type_opera)
        for id in liste:
            try:
                model = Model.objects.get(id=id)
                model.delete()
            except model.DoesNotExist:
                pass
        messages.error(request, f'Vous avez supprimer {len(liste)} {type_opera}')
        return redirect('evangelisation:evangelisation_app_operations', type_opera)
    else:
        return redirect('evangelisation:evangelisation_app_operations', type_opera)


def evangelisation_app_operations_models_modifier(request, type_opera):
    return 



@login_required(login_url="user_login")
def evangelisation_app_operations_modifier(request, type_opera, id):
    model = None
    model = get_model(type_opera)
    instance_model = None
    context = dict()
    form_model = None

evangelisation/templates/pages/liste.html
{% extends 'base.html' %}

{% block titre %}
ASSEMBLE EAUX PAISIBLES | Evangélisations
{% endblock titre %}

{% block hamburger %}
<div class="menu-btn">
    <i class="fas fa-bars"></i>
    <i class="fas fa-times"></i>
</div>
{% endblock hamburger %}

{% block sidebar %}
{% include 'layouts/_sidebar.html' %}
{% endblock sidebar %}



{% block content %}
<div class="wrapper-head-liste">
    <div class="head-liste">
        <h2>Liste des {{type_opera}}</h2>
        <h4>Évangelisations</h4>
    </div>
</div>
<div class="wrapper-liste">
    <div class="row">
        <div class="col-md-2">
            {% include 'partials/operation-side-bar-link.html' %}
        </div>
        <div class="col-md-10">
            {% if messages %}
                {% include 'partials/messages_request.html' %}
            {% endif %}
            {% if has_error %}
                <ul class="form_erros">
                    {{ errors }}
                </ul>
            {% endif %}
                
            <div class="liste">
                {% if type_opera == "personnes" %}
                    <div class="row">
                        <div class="col-md-6 col-xl-3 col-lg-3 col-sm-6">
                            <div class="wrapper-evang-infos">
                                <div class="deja">
                                    <h2><i class="fa fa-user"></i> {{pers_deja|length}}</h2>
                                    <p>Déjà à JÉSUS</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-3 col-lg-3 col-sm-6" >
                            <div class="wrapper-evang-infos">
                                <div class="oui">
                                    <h2><i class="fa fa-user"></i> {{pers_oui|length}}</h2>
                                    <p>Oui à JÉSUS</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-3 col-lg-3 col-sm-6" >
                            <div class="wrapper-evang-infos">
                                <div class="non">
                                    <h2><i class="fa fa-user-slash"></i> {{pers_non|length}}</h2>
                                    <p>Non à JÉSUS</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-3 col-lg-3 col-sm-6">
                            <div class="wrapper-evang-infos">
                                <div class="indecis">
                                    <h2><i class="fa fa-user-slash"></i> {{pers_ras|length}}</h2>
                                    <p>Indécis à JÉSUS</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-xl-4 col-lg-4">
                            <div class="wrapper-evang-infos">
                                <div class="wrapper-whatsapp">
                                    <div class="total-pers">
                                        <h2><i class="fa fa-users"></i> {{models|length}}</h2>
                                        <p>Total</p>
                                    </div>
                                    <div class="whatsapp">
                                        <h2><i class="fa fa-whatsapp"></i> Whatsapp detail</h2>
                                        <div class="oui-whatsapp">
                                            <p>{{pers_whatsapp_oui|length}} ont whatsapp</p>
                                        </div>
                                        <div class="non-whatsapp">
                                            <p style="color:red;">{{pers_whatsapp_non|length}} n'ont pas whatsapp</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <form id="form-suppresion-liste" 
                    action="{% url 'evangelisation:evangelisation_app_operations_models_supprimer' type_opera %}"
                    method="post" class="form-group marg-top">
                    {% csrf_token %}
                    <div class="form-inline form">
                        <div class="form-field form-inline">
                            <label for="suppression">Action : </label>
                            <select name="objects" id="suppression">
                                <option value="---------">
                                    ---------
                                </option>
                                <option value="supprimer">
                                    Supprimer les {% if type_opera == "participants" %}
                                        participants
                                    {% elif type_opera == "sites" %}
                                        sites
                                    {% elif type_opera == "personnes" %}
                                        personnes
                                    {% elif type_opera == "évangelisations" %}
                                        évangelisations
                                    {% endif %}
                                    selectionnés
                                </option>
                            </select>
                            <button type="submit" class="btn btn-success btn-sm" id="btn-liste-delete">envoyer</button>
                            <button type="button" 
                            class="btn btn-default btn-sm" 
                            id="btn-search">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                        <div class="counter-selected">
                            <b>Résultat : </b> <b id="selection" style="color:red;"></b>
                        </div>
                        <div class="wrapper-btn-add">
                            <a class="btn btn-success btn-sm btn-media-query"
                                href="{% url 'evangelisation:evangelisation_app_form_nbre' type_opera %}">
                                <i class="fas fa-plus"></i>
                                Ajouter
                        </a>
                        </div>
                    </div>
                    <div class="search-form">
                        <input type="text" name="query" id="query" 
                            data-url="{% url 'evangelisation:evangelisation_app_operations_recherche' type_opera %}">
                        <b id="result-search"></b>
                    </div>
                    <div class="results" id="results">
                        {% if type_opera == "participants" %}
                            {% include 'pages/participant/liste_participant.html' %}
                        {% elif type_opera == "sites" %}
                            {% include 'pages/site/liste_site.html' %}
                        {% elif type_opera == "personnes" %}
                            <div class="wrapper-zoom">
                                <b>Zoom : </b>
                                <div class="btn-zoom">
                                    <button id="btn-zoom-plus"
                                    type="button" 
                                    class="btn btn-default btn-sm">
                                    +
                                    </button>
                                    <button id="btn-zoom-moins" 
                                    type="button"
                                    class="btn btn-default btn-sm">-</button>
                                </div>
                            </div>
                            {% include 'pages/personne/liste_personne.html' %}
                        {% elif type_opera == "évangelisations" %}
                            {% include 'pages/evangelisation/liste_evangelisation.html' %}
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




<div class="modal fade" id="modal-form">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            
        </div>
    </div>
</div>
{% endblock content %}

evangelisation/templates/pages/modifier.html
{% extends 'base.html' %}

{% block titre %}
ASSEMBLE EAUX PAISIBLES | Evangélisations
{% endblock titre %}

{% block hamburger %}
<div class="menu-btn">
    <i class="fas fa-bars"></i>
    <i class="fas fa-times"></i>
</div>
{% endblock hamburger %}

{% block sidebar %}
{% include 'layouts/_sidebar.html' %}
{% endblock sidebar %}



{% block content %}
<div class="wrapper-head-liste">
    <div class="head-liste">
        <h2>
            Modification de {{form.instance}}
        </h2>
        <h4>Évangelisations</h4>
    </div>
</div>
<div class="wrapper-liste">
    <div class="row">
        <div class="col-md-2">
            {% include 'partials/operation-side-bar-link.html' %}
        </div>
        <div class="col-md-10">
            {% if messages %}
                {% include 'partials/messages_request.html' %}
            {% endif %}
            <div class="liste">
                {% load widget_tweaks %}
                <form id="form-suppresion-liste" 
                        action="{% url 'evangelisation:evangelisation_app_operations_modifier' type_opera instance_model.id %}" 
                        method="post" 
                        class="form-group row">
                    {% csrf_token %}
                        <div class="col-md-6">
                            <div class="wrapper-form_set_item">
                                <h4 class="form-name">formulaire de {{form.instance}}</h4>
                                <div class="form_set_item_field">
                                    {% for field in form %}
                                    <div class="form-group {% if field.errors %}has-error{% endif %}" style="overflow: auto;">
                                        <div class="form-field">
                                            <label for="{{ field.id_for_label }}">{{field.label}}</label> 
                                            {% render_field field class="form-control" %}
                                            <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                                            {% for error in field.errors %}
                                                <p class="pt-2 pb-2 pl-2 pr-2" style="background-color: #e99fa6;">
                                                    {{ error }}
                                                </p>
                                            {% endfor %} 
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="wrapper-btn-formset">
                                <button type="submit" class="btn btn-success">Modifier</button>
                                <a href="{% url 'evangelisation:evangelisation_app_operations' type_opera %}" class="btn btn-secondary">Annuler</a>
                            </div>
                        </div>
                    </div>
                </form>
                    
            </div>
        </div>
    </div>
</div>


{% endblock content %}

evangelisation/templates/pages/supprimer.html
{% extends 'base.html' %}

{% block titre %}
ASSEMBLE EAUX PAISIBLES | Evangélisations | {{type_opera}}
{% endblock titre %}

{% block hamburger %}
<div class="menu-btn">
    <i class="fas fa-bars"></i>
    <i class="fas fa-times"></i>
</div>
{% endblock hamburger %}

{% block sidebar %}
{% include 'layouts/_sidebar.html' %}
{% endblock sidebar %}



{% block content %}
<div class="wrapper-head-liste">
    <div class="head-liste">
        <h2>
            Liste des
            {% if type_opera == "participants" %}
                participants
            {% elif type_opera == "sites" %}
                sites
            {% elif type_opera == "personnes" %}
                personnes
            {% elif type_opera == "évangelisations" %}
                évangelisations
            {% endif %} à supprimer({{ models|length }})
        </h2>
        <h4>{{type_opera}}</h4>
    </div>
</div>
<div class="wrapper-liste">
    <div class="row">
        <div class="col-md-12">

            <div class="liste">
                <h2 class="text-muted">Êtes-vous sûr ?</h2>
                <p>
                    Voulez-vous vraiment supprimer les
                    {% if type_opera == "participants" %}
                        participants
                    {% elif type_opera == "sites" %}
                        sites
                    {% elif type_opera == "personnes" %}
                        personnes
                    {% elif type_opera == "évangelisations" %}
                        évangelisations
                    {% endif %} sélectionnés ? Tous les objets suivants et les
                    éléments liés seront supprimés :
                </p>
                <div class="resume">
                    <h4>
                        <b>Résumé</b>
                    </h4>
                    <ul>
                        <li>
                            {% if type_opera == "participants" %}
                                participants : {{ models|length }}
                            {% elif type_opera == "sites" %}
                                sites : {{ models|length }}
                            {% elif type_opera == "personnes" %}
                                personnes : {{ models|length }}
                            {% elif type_opera == "évangelisations" %}
                                évangelisations : {{ models|length }}
                            {% endif %} 
                        </li>
                    </ul>
                </div>
                <div class="liste-utilisateur-suppr">
                    <h4>
                        <b>Les {% if type_opera == "participants" %}
                            participants
                        {% elif type_opera == "sites" %}
                            sites
                        {% elif type_opera == "personnes" %}
                            personnes 
                        {% elif type_opera == "évangelisations" %}
                            évangelisations
                        {% endif %}</b>
                    </h4>
                    <ul>
                        {% for model in models %}
                        <li>
                            {% if type_opera == "participants" %}
                                participant {{forloop.counter}} : 
                            {% elif type_opera == "sites" %}
                                site {{forloop.counter}} :
                            {% elif type_opera == "personnes" %}
                                personne {{forloop.counter}} :
                            {% elif type_opera == "évangelisations" %}
                                évangelisation {{forloop.counter}} :
                            {% endif %}
                            <a class="suppr-user" href="#">{{ model }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <form 
                    id="form-suppresion-liste" 
                    action="{% url 'evangelisation:evangelisation_app_operations_supprimer' type_opera %}" 
                    method="post" 
                    class="form-group">
                    {% csrf_token %}
                    <div class="results">
                        {% for model in models %}
                            <input 
                                hidden 
                                type="text" 
                                name="user_selected" 
                                value="{{model.id}}">
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" 
                                class="btn btn-danger btn-sm">
                                Supprimers
                            </button>
                            <a 
                                href="{% url 'evangelisation:evangelisation_app_operations' type_opera %}" 
                                class="btn btn-secondary btn-sm">
                                Annuler
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}